((display) 10)
((lambda (x) (display x)) 11)
(display (+ 1 2))
(display ((lambda (x) (+ 2 x)) 10))
(display ((+ 2) 3))
((lambda (x y) (display (+ x y))) 7 8)
((lambda (x y) (display (+ x y))) 7 (+ 1 2))
(display (+ 1 (+ (+ 2 5) 3)))
(display ((lambda (x) x) 5))
(display (((lambda (x y) (+ x y)) 10) 20))
(display ((lambda () (+ 1 2))))
(display ((((lambda (x) (lambda (y) (lambda (z) (+ x (+ y z))))) 1) 2) 3))
