((print) 10)
((lambda (x) (print x)) 11)
(print (add 1 2))
(print ((lambda (x) (add 2 x)) 10))
(print ((add 2) 3))
((lambda (x y) (print (add x y))) 7 8)
((lambda (x y) (print (add x y))) 7 (add 1 2))
(print (add 1 (add (add 2 5) 3)))
(print ((lambda (x) x) 5))
(print (((lambda (x y) (add x y)) 10) 20))
(print (lambda () (1)))
